// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Power.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Abbbd3832Ad747A0A1B0Cd1B3C6D6579 {

  /// <summary>Holder for reflection information generated from Power.proto</summary>
  public static partial class PowerReflection {

    #region Descriptor
    /// <summary>File descriptor for Power.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PowerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtQb3dlci5wcm90bxIhX2FiYmJkMzgzMmFkNzQ3YTBhMWIwY2QxYjNjNmQ2",
            "NTc5Iv0CCgZDb25maWcSQwoIcHJvZmlsZXMYASADKAsyMS5fYWJiYmQzODMy",
            "YWQ3NDdhMGExYjBjZDFiM2M2ZDY1NzkuQ29uZmlnLlByb2ZpbGUSOwoDcGR1",
            "GAIgASgOMi4uX2FiYmJkMzgzMmFkNzQ3YTBhMWIwY2QxYjNjNmQ2NTc5LkNv",
            "bmZpZy5QZHUxGqYBCgdQcm9maWxlEkYKBXN0YXRlGAIgASgOMjcuX2FiYmJk",
            "MzgzMmFkNzQ3YTBhMWIwY2QxYjNjNmQ2NTc5LkNvbmZpZy5Qcm9maWxlLlN0",
            "YXRlEhMKC3dha2V1cF9tYXNrGAMgASgNEg8KB2RlbGF5X3MYBCABKA0iLQoF",
            "U3RhdGUSCgoGQUNUSVZFEAASCQoFU0xFRVAQARINCglISUJFUk5BVEUQAiId",
            "CghCYXVkUmF0ZRIHCgNMT1cQABIICgRISUdIEAEiKQoEUGR1MRIKCgZFTkFC",
            "TEUQABILCgdESVNBQkxFEAESCAoEVEVTVBACKikKCUFsbG9jYXRvchIRCg1E",
            "T19OT1RfUkVNT1ZFEAASCQoFVkFMVUUQASpFChJTdGFuZGFyZEV2ZW50Q29k",
            "ZXMSDAoIUE9XRVJfVVAQABILCgdXQUtFX1VQEAESFAoQUE9XRVJfT1JfV0FL",
            "RV9VUBACKkUKE1N0YW5kYXJkRmlsdGVyQ29kZXMSFgoSSVNfQ1VSUkVOVF9Q",
            "Uk9GSUxFEAASFgoSSVNfUkVTVFJJQ1RFRF9NT0RFEAEqKAoTU3RhbmRhcmRB",
            "Y3Rpb25Db2RlcxIRCg1BUFBMWV9QUk9GSUxFEABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Allocator), typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.StandardEventCodes), typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.StandardFilterCodes), typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.StandardActionCodes), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config), global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Parser, new[]{ "Profiles", "Pdu" }, null, new[]{ typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.BaudRate), typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile), global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Parser, new[]{ "State", "WakeupMask", "DelayS" }, null, new[]{ typeof(global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State) }, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum Allocator {
    /// <summary>
    /// This needs to be here as a zero value.
    /// </summary>
    [pbr::OriginalName("DO_NOT_REMOVE")] DoNotRemove = 0,
    [pbr::OriginalName("VALUE")] Value = 1,
  }

  public enum StandardEventCodes {
    /// <summary>
    /// Signal: N/A
    /// </summary>
    [pbr::OriginalName("POWER_UP")] PowerUp = 0,
    /// <summary>
    /// Signal: N/A
    /// </summary>
    [pbr::OriginalName("WAKE_UP")] WakeUp = 1,
    /// <summary>
    /// Signal: N/A
    /// </summary>
    [pbr::OriginalName("POWER_OR_WAKE_UP")] PowerOrWakeUp = 2,
  }

  public enum StandardFilterCodes {
    /// <summary>
    /// Signal: The current profile.
    /// </summary>
    [pbr::OriginalName("IS_CURRENT_PROFILE")] IsCurrentProfile = 0,
    /// <summary>
    /// Signal: The restricted mode
    /// 0 - unrestricted
    /// 1 - restricted
    /// 2 - transport
    /// 3 - invalid
    /// </summary>
    [pbr::OriginalName("IS_RESTRICTED_MODE")] IsRestrictedMode = 1,
  }

  public enum StandardActionCodes {
    /// <summary>
    /// Signal: The profile to apply.
    /// </summary>
    [pbr::OriginalName("APPLY_PROFILE")] ApplyProfile = 0,
  }

  #endregion

  #region Messages
  public sealed partial class Config : pb::IMessage<Config>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.PowerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config(Config other) : this() {
      profiles_ = other.profiles_.Clone();
      pdu_ = other.pdu_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "profiles" field.</summary>
    public const int ProfilesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile> _repeated_profiles_codec
        = pb::FieldCodec.ForMessage(10, global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Parser);
    private readonly pbc::RepeatedField<global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile> profiles_ = new pbc::RepeatedField<global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile>();
    /// <summary>
    /// The profile's 3 state.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile> Profiles {
      get { return profiles_; }
    }

    /// <summary>Field number for the "pdu" field.</summary>
    public const int PduFieldNumber = 2;
    private global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1 pdu_ = global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1.Enable;
    /// <summary>
    /// Protocol Data Units message format.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1 Pdu {
      get { return pdu_; }
      set {
        pdu_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!profiles_.Equals(other.profiles_)) return false;
      if (Pdu != other.Pdu) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= profiles_.GetHashCode();
      if (Pdu != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1.Enable) hash ^= Pdu.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      profiles_.WriteTo(output, _repeated_profiles_codec);
      if (Pdu != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1.Enable) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Pdu);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      profiles_.WriteTo(ref output, _repeated_profiles_codec);
      if (Pdu != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1.Enable) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Pdu);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += profiles_.CalculateSize(_repeated_profiles_codec);
      if (Pdu != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1.Enable) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Pdu);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      profiles_.Add(other.profiles_);
      if (other.Pdu != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1.Enable) {
        Pdu = other.Pdu;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            profiles_.AddEntriesFrom(input, _repeated_profiles_codec);
            break;
          }
          case 16: {
            Pdu = (global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            profiles_.AddEntriesFrom(ref input, _repeated_profiles_codec);
            break;
          }
          case 16: {
            Pdu = (global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Pdu1) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Config message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum BaudRate {
        /// <summary>
        /// Slow rate (250 KBPS).
        /// </summary>
        [pbr::OriginalName("LOW")] Low = 0,
        /// <summary>
        /// Fast rate (500 KBPS).
        /// </summary>
        [pbr::OriginalName("HIGH")] High = 1,
      }

      public enum Pdu1 {
        /// <summary>
        /// Enable the Pdu1 PGN Mask.
        /// </summary>
        [pbr::OriginalName("ENABLE")] Enable = 0,
        /// <summary>
        /// Disable the Pdu1 PGN Mask.
        /// </summary>
        [pbr::OriginalName("DISABLE")] Disable = 1,
        [pbr::OriginalName("TEST")] Test = 2,
      }

      public sealed partial class Profile : pb::IMessage<Profile>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Profile> _parser = new pb::MessageParser<Profile>(() => new Profile());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Profile> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Profile() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Profile(Profile other) : this() {
          state_ = other.state_;
          wakeupMask_ = other.wakeupMask_;
          delayS_ = other.delayS_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Profile Clone() {
          return new Profile(this);
        }

        /// <summary>Field number for the "state" field.</summary>
        public const int StateFieldNumber = 2;
        private global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State state_ = global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State.Active;
        /// <summary>
        /// The profile's 1 state.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State State {
          get { return state_; }
          set {
            state_ = value;
          }
        }

        /// <summary>Field number for the "wakeup_mask" field.</summary>
        public const int WakeupMaskFieldNumber = 3;
        private uint wakeupMask_;
        /// <summary>
        /// What will wake the device up (input, adc_threshold, cell, etc).
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint WakeupMask {
          get { return wakeupMask_; }
          set {
            wakeupMask_ = value;
          }
        }

        /// <summary>Field number for the "delay_s" field.</summary>
        public const int DelaySFieldNumber = 4;
        private uint delayS_;
        /// <summary>
        /// How long to wait before applying this profile in seconds.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint DelayS {
          get { return delayS_; }
          set {
            delayS_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Profile);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Profile other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (State != other.State) return false;
          if (WakeupMask != other.WakeupMask) return false;
          if (DelayS != other.DelayS) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (State != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State.Active) hash ^= State.GetHashCode();
          if (WakeupMask != 0) hash ^= WakeupMask.GetHashCode();
          if (DelayS != 0) hash ^= DelayS.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (State != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State.Active) {
            output.WriteRawTag(16);
            output.WriteEnum((int) State);
          }
          if (WakeupMask != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(WakeupMask);
          }
          if (DelayS != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(DelayS);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (State != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State.Active) {
            output.WriteRawTag(16);
            output.WriteEnum((int) State);
          }
          if (WakeupMask != 0) {
            output.WriteRawTag(24);
            output.WriteUInt32(WakeupMask);
          }
          if (DelayS != 0) {
            output.WriteRawTag(32);
            output.WriteUInt32(DelayS);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (State != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State.Active) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
          }
          if (WakeupMask != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WakeupMask);
          }
          if (DelayS != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DelayS);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Profile other) {
          if (other == null) {
            return;
          }
          if (other.State != global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State.Active) {
            State = other.State;
          }
          if (other.WakeupMask != 0) {
            WakeupMask = other.WakeupMask;
          }
          if (other.DelayS != 0) {
            DelayS = other.DelayS;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 16: {
                State = (global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State) input.ReadEnum();
                break;
              }
              case 24: {
                WakeupMask = input.ReadUInt32();
                break;
              }
              case 32: {
                DelayS = input.ReadUInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 16: {
                State = (global::Abbbd3832Ad747A0A1B0Cd1B3C6D6579.Config.Types.Profile.Types.State) input.ReadEnum();
                break;
              }
              case 24: {
                WakeupMask = input.ReadUInt32();
                break;
              }
              case 32: {
                DelayS = input.ReadUInt32();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Profile message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public enum State {
            [pbr::OriginalName("ACTIVE")] Active = 0,
            [pbr::OriginalName("SLEEP")] Sleep = 1,
            [pbr::OriginalName("HIBERNATE")] Hibernate = 2,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
